version: '3'
services:
  postgres:
    image: library/postgres:12.1-alpine
    restart: unless-stopped
    ports:
    - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
  
  # backend:
  #   build: 
  #     context: ./
  #   ports:
  #     - 4132:4132
  #   restart: unless-stopped
  #   environment: 
  #     DB_HOST: postgres
  #   depends_on: 
  #     - postgres

  